In [ ]:
#!pip install numpy pandas matplotlib torch deeplay ipywidgets

  Using cached numpy-2.4.4-cp314-cp314-win_amd64.whl.metadata (6.6 kB)
  Using cached pandas-3.0.2-cp314-cp314-win_amd64.whl.metadata (19 kB)
  Using cached matplotlib-3.10.9-cp314-cp314-win_amd64.whl.metadata (52 kB)
  Using cached torch-2.11.0-cp314-cp314-win_amd64.whl.metadata (29 kB)
  Using cached deeplay-0.1.4-py3-none-any.whl.metadata (13 kB)
  Using cached ipywidgets-8.1.8-py3-none-any.whl.metadata (2.4 kB)
  Using cached tzdata-2026.2-py2.py3-none-any.whl.metadata (1.4 kB)
  Using cached contourpy-1.3.3-cp314-cp314-win_amd64.whl.metadata (5.5 kB)
  Using cached cycler-0.12.1-py3-none-any.whl.metadata (3.8 kB)
  Using cached fonttools-4.62.1-cp314-cp314-win_amd64.whl.metadata (119 kB)
  Using cached kiwisolver-1.5.0-cp314-cp314-win_amd64.whl.metadata (5.2 kB)
  Using cached pillow-12.2.0-cp314-cp314-win_amd64.whl.metadata (9.0 kB)
  Using cached pyparsing-3.3.2-py3-none-any.whl.metadata (5.8 kB)
  Using cached filelock-3.29.0-py3-none-any.whl.metadata (2.0 kB)
  Using cached ty

In [1]:
import h5py as h5

# Tienes que decirle la ruta completa donde lo guardamos
ruta_lectura = r"C:\Users\MSI\Downloads\Proyecto_Fluidos_AI\datos_procesados\process_data.h5"

# Ahora sí, ábrelo en modo lectura ('r')
hf = h5.File(ruta_lectura, 'r')

print("¡Archivo abierto con éxito!")
print("Carpetas encontradas dentro:", list(hf.keys()))

¡Archivo abierto con éxito!
Carpetas encontradas dentro: ['data_analisis', 'header', 'sta', 'stats_zscore']


In [2]:
hf.keys()

<KeysViewHDF5 ['data_analisis', 'header', 'sta', 'stats_zscore']>

In [3]:
hf['header'].keys()

<KeysViewHDF5 ['Re', 'alp', 'bet', 'mx', 'my', 'mz', 'nacum', 'probe_j', 'time', 'timev', 'vcon', 'y']>

In [4]:
hf['sta'].keys()

<KeysViewHDF5 ['probe_u', 'probe_v', 'probe_w', 'utmp', 'vtmp', 'wtmp']>

In [5]:
hf['stats_zscore'].keys()

<KeysViewHDF5 ['media_u', 'media_utmp', 'media_v', 'media_vtmp', 'media_w', 'media_wtmp', 'std_u', 'std_utmp', 'std_v', 'std_vtmp', 'std_w', 'std_wtmp']>

In [6]:
hf['data_analisis'].keys()

<KeysViewHDF5 ['mapa_coherencia_u', 'mapa_coherencia_v', 'mapa_coherencia_w', 'u_fluc', 'u_local_media', 'v_fluc', 'v_local_media', 'w_fluc', 'w_local_media']>

In [6]:
timev = hf['header']['timev'][()]
timev

array([0.0000e+00, 1.0000e-02, 2.0000e-02, ..., 9.8997e+02, 9.8998e+02,
       9.8999e+02], shape=(106000,), dtype=float32)

In [ ]:
hf['header']['Re'][()]

array([2100.])

In [9]:
for key in hf['header'].keys():
    print(key,hf['header'][key][()])

Re [2100.]
alp [0.25]
bet [0.66666667]
mx [256]
my [201]
mz [191]
nacum [0]
probe_j [  5  26  71 101 131 176 197]
time [9.99999978]
timev [0.0000000e+00 9.9999998e-03 2.0000000e-02 ... 6.9970001e+01 6.9979996e+01
 6.9989998e+01]
vcon [0.]
y [-1.         -0.99725468 -0.99422326 -0.99091432 -0.98733595 -0.98349586
 -0.97940138 -0.97505944 -0.97047669 -0.96565943 -0.96061371 -0.95534529
 -0.94985968 -0.94416216 -0.93825781 -0.93215149 -0.92584788 -0.91935147
 -0.91266659 -0.90579741 -0.89874799 -0.89152221 -0.88412385 -0.87655656
 -0.86882387 -0.86092923 -0.85287599 -0.84466741 -0.83630665 -0.8277968
 -0.81914088 -0.81034185 -0.8014026  -0.79232597 -0.78311475 -0.77377166
 -0.76429938 -0.75470058 -0.74497786 -0.7351338  -0.72517096 -0.71509186
 -0.70489898 -0.69459482 -0.68418182 -0.67366244 -0.6630391  -0.65231423
 -0.64149023 -0.63056952 -0.61955448 -0.60844751 -0.59725101 -0.58596737
 -0.57459899 -0.56314826 -0.55161758 -0.54000934 -0.52832595 -0.51656981
 -0.50474335 -0.49284897 -0.48

In [7]:
hf['header']['probe_j'][()]

array([  5,  26,  71, 101, 131, 176, 197], dtype=int32)

In [8]:
hf['sta']['probe_u'][()].shape

(106000, 7, 288)

In [12]:
y=hf['header']['y'][()]
probe_j=hf['header']['probe_j'][()]

In [13]:
probe_j

array([  5,  26,  71, 101, 131, 176, 197], dtype=int32)

In [14]:
hf['sta']['utmp'][()].shape

(7000, 201)

In [15]:
hf['header']['y'][()].shape

(201,)

In [16]:
hf['header']['mz'][()]

array([191], dtype=int32)

In [17]:
hf['header']['timev'][()].shape

(7000,)

In [18]:
for key in hf['sta'].keys():
    print(key,hf['sta'][key][()].shape)

probe_u (7000, 7, 288)
probe_v (7000, 7, 288)
probe_w (7000, 7, 288)
utmp (7000, 201)
vtmp (7000, 201)
wtmp (7000, 201)
